import * as fs from "fs";
import * as path from "path";
import { db } from "../src/core/database.js";

async function generateArchitecture() {
  const tables = db.prepare("SELECT name, sql FROM sqlite_master WHERE type='table'").all() as { name: string, sql: string }[];
  
  let mermaid = "```mermaid\nerDiagram\n";
  let schemaDetails = "";

  for (const table of tables) {
    if (table.name === "sqlite_sequence") continue;
    
    mermaid += `    ${table.name} {\n`;
    
    // Parse basic columns from sql string for diagram
    const cols = table.sql.match(/\((.*)\)/s);
    if (cols && cols.length > 1) {
      const matchStr = cols[1] || "";
      const lines = matchStr.split(",").map(l => l.trim()).filter(l => Boolean(l) && !l.toUpperCase().startsWith("PRIMARY") && !l.toUpperCase().startsWith("FOREIGN"));
      for (const line of lines) {
        const parts = line.split(/\s+/);
        if (parts.length >= 2) {
          const colName = parts[0]!.replace(/['"]/g, '');
          const colType = parts[1]!;
          mermaid += `        ${colType} ${colName}\n`;
        }
      }
    }
    mermaid += `    }\n`;
    
    schemaDetails += `### \`${table.name}\`\n\`\`\`sql\n${table.sql}\n\`\`\`\n\n`;
  }
  mermaid += "```\n";

  const content = `# Living Database Architecture\n\nThis artifact is auto-generated by \`npm run build:architecture\` to keep Antigravity context perfectly aligned with the SQLite schema.\n\n## Entity Relationship Diagram\n\n${mermaid}\n\n## Schema Definitions\n\n${schemaDetails}`;

  const outPath = path.resolve(process.cwd(), "architecture.md");
  fs.writeFileSync(outPath, content);
  console.log(`✅ Architecture generated at ${outPath}`);
}

generateArchitecture().catch(console.error);
